name: Deploy to Vercel
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull Vercel environment
        run: npx vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"
      - name: Deploy (Vercel builds automatically)
        run: npx vercel --prod --token="${{ secrets.VERCEL_TOKEN }}"
